"""runtime boundary for hosted preview vs gb10 execution."""

from __future__ import annotations

import os
from typing import Any

import httpx


GB10_RUNTIME_URL = os.getenv("FUZE_GB10_RUNTIME_URL", "").rstrip("/")
GB10_RUNTIME_TOKEN = os.getenv("FUZE_GB10_RUNTIME_TOKEN", "")
HOSTED_PREVIEW = os.getenv("VERCEL") == "1" or os.getenv("FUZE_HOSTED_PREVIEW", "0") == "1"
OLLAMA_HOST = os.getenv("OLLAMA_HOST", "http://127.0.0.1:11434")
LOCAL_LLM_MODEL = os.getenv("FUZE_LOCAL_LLM_MODEL", "qwen3:8b")
LOCAL_LLM_ENABLED = os.getenv("FUZE_ENABLE_LOCAL_LLM", "0") == "1"


def configured() -> bool:
    return bool(GB10_RUNTIME_URL)


def headers() -> dict[str, str]:
    if not GB10_RUNTIME_TOKEN:
        return {}
    return {"authorization": f"bearer {GB10_RUNTIME_TOKEN}"}


def with_proxy_marker(payload: Any, path: str) -> Any:
    if isinstance(payload, dict):
        return {
            **payload,
            "_runtime_proxy": {
                "execution": "gb10_runtime",
                "url": GB10_RUNTIME_URL,
                "path": path,
            },
        }
    return payload


async def proxy_json(
    method: str,
    path: str,
    json_body: dict[str, Any] | None = None,
    timeout: float = 60,
) -> Any:
    """forward a runtime request to the secured gb10 api."""
    async with httpx.AsyncClient(timeout=timeout, headers=headers()) as client:
        response = await client.request(method, f"{GB10_RUNTIME_URL}{path}", json=json_body)
        response.raise_for_status()
    return with_proxy_marker(response.json(), path)


async def gb10_status() -> dict[str, Any]:
    """report whether this process can reach a secured gb10 runtime."""
    if not configured():
        if not HOSTED_PREVIEW:
            return {
                "configured": False,
                "reachable": True,
                "execution": "local_runtime",
                "message": "running inside the local fuze runtime; no upstream gb10 url needed.",
            }
        return {
            "configured": False,
            "reachable": False,
            "execution": "hosted_preview",
            "message": "no FUZE_GB10_RUNTIME_URL configured; prod is using synthetic demo data locally in vercel.",
        }

    try:
        async with httpx.AsyncClient(timeout=2.5, headers=headers()) as client:
            response = await client.get(f"{GB10_RUNTIME_URL}/health")
            response.raise_for_status()
        payload = response.json()
        return {
            "configured": True,
            "reachable": True,
            "execution": "gb10_runtime",
            "url": GB10_RUNTIME_URL,
            "authenticated": bool(GB10_RUNTIME_TOKEN),
            "remote": {
                "ok": payload.get("ok"),
                "cloud_llm_calls": payload.get("cloud_llm_calls"),
                "ollama": payload.get("ollama", {}),
                "qdrant": payload.get("qdrant", {}),
                "always_on": payload.get("always_on", {}),
            },
        }
    except Exception as exc:
        return {
            "configured": True,
            "reachable": False,
            "execution": "gb10_runtime_unreachable",
            "url": GB10_RUNTIME_URL,
            "authenticated": bool(GB10_RUNTIME_TOKEN),
            "error": str(exc),
        }


def local_execution_mode() -> dict[str, Any]:
    if configured():
        return {
            "mode": "gb10_runtime_configured",
            "provider": "secured gb10 runtime",
            "inference": "remote local ollama behind private access boundary",
        }
    if not HOSTED_PREVIEW:
        return {
            "mode": "local_runtime",
            "provider": "local fuze runtime",
            "inference": "local ollama/qdrant available on this machine when services are online",
        }
    return {
        "mode": "hosted_preview",
        "provider": "deterministic demo engine",
        "inference": "none; responses are assembled from synthetic sample data",
    }


def local_inference_probe(goal: str, readiness_score: int | None = None) -> dict[str, Any]:
    """optionally prove a local ollama model generated text on this machine."""
    if not LOCAL_LLM_ENABLED:
        return {
            "enabled": False,
            "available": False,
            "model": LOCAL_LLM_MODEL,
            "reason": "set FUZE_ENABLE_LOCAL_LLM=1 on the runtime host to force a local generation proof",
        }

    prompt = (
        "Reply with one short sentence. "
        "Say this grant-readiness run was generated by local fuze inference on the dell. "
        f"Goal: {goal}. Readiness score: {readiness_score}."
    )
    try:
        with httpx.Client(timeout=25) as client:
            response = client.post(
                f"{OLLAMA_HOST}/api/generate",
                json={
                    "model": LOCAL_LLM_MODEL,
                    "prompt": prompt,
                    "stream": False,
                    "think": False,
                    "options": {"temperature": 0, "num_predict": 48},
                },
            )
            response.raise_for_status()
        payload = response.json()
        return {
            "enabled": True,
            "available": True,
            "provider": "ollama",
            "host": OLLAMA_HOST,
            "model": LOCAL_LLM_MODEL,
            "response": payload.get("response", "").strip(),
            "cloud_calls": 0,
        }
    except Exception as exc:
        return {
            "enabled": True,
            "available": False,
            "provider": "ollama",
            "host": OLLAMA_HOST,
            "model": LOCAL_LLM_MODEL,
            "error": str(exc),
            "cloud_calls": 0,
        }


async def local_chat_completion(prompt: str, *, max_tokens: int = 420) -> dict[str, Any]:
    """generate the actual chat answer with the local ollama model when enabled."""
    if not LOCAL_LLM_ENABLED:
        return {
            "enabled": False,
            "available": False,
            "model": LOCAL_LLM_MODEL,
            "reason": "set FUZE_ENABLE_LOCAL_LLM=1 on the runtime host to enable local chat generation",
            "cloud_calls": 0,
        }

    try:
        async with httpx.AsyncClient(timeout=60) as client:
            response = await client.post(
                f"{OLLAMA_HOST}/api/generate",
                json={
                    "model": LOCAL_LLM_MODEL,
                    "prompt": prompt,
                    "stream": False,
                    "think": False,
                    "options": {
                        "temperature": 0.2,
                        "num_predict": max_tokens,
                        "top_p": 0.9,
                    },
                },
            )
            response.raise_for_status()
        payload = response.json()
        return {
            "enabled": True,
            "available": True,
            "provider": "ollama",
            "host": OLLAMA_HOST,
            "model": LOCAL_LLM_MODEL,
            "response": payload.get("response", "").strip(),
            "cloud_calls": 0,
        }
    except Exception as exc:
        return {
            "enabled": True,
            "available": False,
            "provider": "ollama",
            "host": OLLAMA_HOST,
            "model": LOCAL_LLM_MODEL,
            "error": str(exc),
            "cloud_calls": 0,
        }
